version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
      - 3001:3000
      - 3002:3000
      - 3003:3000
      - 3004:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build: ./backend
    ports:
      - 4010:4010
    volumes:
      - ./backend:/app
      - /app/node_modules